name: Run PowerShell Script Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes (UTC)
  workflow_dispatch:       # Allows manual trigger

jobs:
  run-powershell:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run PowerShell script
        shell: pwsh
        run: |
          ./application_response.ps1
